### ISSUE TITLE
How to use caddy to reverse it

### ISSUE THREAD

**Issue by Kaze1027** [Jackzmc/l4d2-stats-plugin#29]
I want to use caddy as frontend to process web pages, can you show me how to config it? I've tried, but it comes error that "Invalid Host header"
![image](https://github.com/Jackzmc/l4d2-stats-plugin/assets/51438620/1c73338c-3adb-4533-bda3-e9b33616595f)

**Comment by Jackzmc** [comment]
I'm not super familiar with caddy, but you do need to rewrite the Host header for the express server to accept it.

From quick googling, it looks like you can do this:
```
reverse_proxy ... {
    Host {upstream_hostport}
    ...
}
```
[reverse_proxy](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#https)

**Comment by Kaze1027** [comment]
Thank you for your reply, I've build website, but here are some error info I found, is that My database mysql is mysql8.0? Does it support mysql8.0?

**Comment by Jackzmc** [comment]
You didn't submit any error info. MySQL 8 seems to be pretty old, my server is running 15, but I need your error info

**Comment by Jackzmc** [comment]
I think you have an old version of the tables. This is more of a personal project, so I've neglected updating some things.

The stats_database.sql should be up to date now, it will recreate the tables tho (losing any data)

**Comment by Jackzmc** [comment]
And yeah the play style and rating will not work, that is custom for my system.

**Comment by Kaze1027** [comment]
I greatly appreciate for your work, it's fine that I'll rebuild my satabase, there is no data now except test data. I'm gonna try it.      : )
