### ISSUE TITLE
Plugin compilation errors and development suggestions

### ISSUE THREAD

**Issue by PIPDesign** [Jackzmc/l4d2-stats-plugin#35]
Hey, I watched your web demo and your plugin is just so cool.
But I encountered the following error when compiling the plugin.
```
jutils.inc(191) : error 101: fixed dimensions must be after the array name, not on the type
 error 417: cannot read from file: "l4d_info_editor"
```
I noticed that the contents of the jutils.inc file are missing, did you forget to upload it? Also, can you provide l4d_info_editor.inc file？

**Suggestion:** I think the number of points that players can earn can be modified with convar, which will allow you to have more flexibility in your plugin, such as adapting to different game difficulties and mutation modes.

**Comment by Jackzmc** [comment]
My actual development of this plugin is done in my [sourcemod-plugins](https://github.com/Jackzmc/sourcemod-plugins/) repo folder, so sometimes the dependencies in this repo get over looked and outdated, so take a look there if there's something missing or outdated.

I pushed the l4d_info_editor and updated jutils.

I'm actually planning to entirely redo the points system to be computed live by the webserver instead of incremented in-game but I only work on this periodically. Might be easy to let you configure the weights of every statistic it pulls from a config file, we will see.

**Comment by PIPDesign** [comment]
Awesome, thanks for explaining in detail, you will do it to the next level

**Comment by PIPDesign** [comment]
Another error occurred when the plugin was compiling **l4d2_stats_recorder.sp**, I didn't find a workaround on the web, how do I fix it?
```
\Souecemod\1.11\left4dead2\addons\sourcemod\scripting\include\stats\heatmaps.sp(270) : error 105: cannot find method or property "Game.name"
//
// 1 Error.
//
// Compilation Time: 0.81 sec
```

**Comment by PIPDesign** [comment]
It works!
`//SourceMod Batch Compiler
// by the SourceMod Dev Team


//// l4d2_stats_recorder.sp
//
// D:\YangZhixun\OneDrive - 陕西科技大学\求生之路\Souecemod\1.11\left4dead2\addons\sourcemod\scripting\include\stats\heatmaps.sp(220) : warning 203: symbol is never used: "type"
// Code size:         80912 bytes
// Data size:         40316 bytes
// Stack/heap size:      20604 bytes
// Total requirements:  141832 bytes
//
// 1 Warning.
//
// Compilation Time: 0.89 sec
// ----------------------------------------

Press enter to exit ...`

**Comment by PIPDesign** [comment]
It works !Thankyou
`//SourceMod Batch Compiler
// by the SourceMod Dev Team


//// l4d2_stats_recorder.sp
//
// D:\YangZhixun\OneDrive\Souecemod\1.11\left4dead2\addons\sourcemod\scripting\include\stats\heatmaps.sp(220) : warning 203: symbol is never used: "type"
// Code size:         80912 bytes
// Data size:         40316 bytes
// Stack/heap size:      20604 bytes
// Total requirements:  141832 bytes
//
// 1 Warning.
//
// Compilation Time: 0.89 sec
// ----------------------------------------

Press enter to exit ...`

**Comment by PIPDesign** [comment]
It works,thankyou!
`//SourceMod Batch Compiler
// by the SourceMod Dev Team


//// l4d2_stats_recorder.sp
//
// D:\Souecemod\1.11\left4dead2\addons\sourcemod\scripting\include\stats\heatmaps.sp(220) : warning 203: symbol is never used: "type"
// Code size:         80912 bytes
// Data size:         40316 bytes
// Stack/heap size:      20604 bytes
// Total requirements:  141832 bytes
//
// 1 Warning.
//
// Compilation Time: 0.89 sec
// ----------------------------------------

Press enter to exit ...`
